swagger: "2.0"
info:
  description: ""
  version: "1.0.0"
  title: "Swagger BIG DataAnalyzer"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "bod.denes@gmail.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "localhost"
basePath: "/big"
tags:
  - name: "Metadata"
  - name: "Data"
schemes:
- "http"
paths:
  /metadata/datasources:
    get:
      tags:
        - "Metadata"
      summary: "List all datastores"
      description: ""
      produces:
        - "application/json"
      responses:
        200:
          description: ""
          schema:
            $ref: "#/definitions/Datasources"
  /metadata/datasource/{datasourceId}:
    get:
      tags:
        - "Metadata"
      produces:
        - "application/json"
      parameters:
        - name: "datasourceId"
          in: "path"
          description: "ID of datasource that needs to be fetched"
          required: true
          type: "string"
      responses:
        200:
          description: "Ok"
          schema:
            $ref: "#/definitions/Datasource"
        404:
          description: "Datasource not found"
  /metadata/datasource/{datasourceId}/kpi/list:
    get:
      tags:
        - "Metadata"
      produces:
        - "application/json"
      parameters:
        - name: "datasourceId"
          in: "path"
          description: ""
          required: true
          type: "string"
      responses:
        200:
          description: "Ok"
          schema:
            $ref: "#/definitions/KpiList"
        404:
          description: "Datasource not found"

  /metadata/datasource/{datasourceId}/dimension/list:
    get:
      tags:
        - "Metadata"
      produces:
        - "application/json"
      parameters:
        - name: "datasourceId"
          in: "path"
          description: ""
          required: true
          type: "string"
      responses:
        200:
          description: "Ok"
          schema:
            $ref: "#/definitions/DimensionList"
        404:
          description: "Datasource not found"
  /data:
    post:
      tags:
        - "Data"
      consumes:
        - "application/json"
      produces:
        - "application/json"
        - "text/csv"
      parameters:
        - in: "body"
          name: "body"
          schema:
            $ref: "#/definitions/DataRequest"
      responses:
        200:
          description: "Ok"
          schema:
            $ref: "#/definitions/DataResponse"
        404:
          description: "Datasource not found"

definitions:
  Datasources:
    type: "array"
    items:
      $ref: "#/definitions/Datasource"

  Datasource:
    type: "object"
    properties:
      name:
        type: "string"
      displayName:
        type: "string"
      beginning:
        type: "integer"
      end:
        type: "integer"

  KpiList:
    type: "array"
    items:
      $ref: "#/definitions/Kpi"

  Kpi:
    type: "object"
    properties:
      name:
        type: "string"
      displayName:
        type: "string"
      offeredMetric:
        type: "string"
      unit:
        type: "string"

  DimensionList:
    type: "array"
    items:
      $ref: "#/definitions/Dimension"

  Dimension:
    type: "object"
    properties:
      name:
        type: "string"
      displayName:
        type: "string"
      unit:
        type: "string"

  DataRequest:
    type: "object"
    properties:
      datasource:
        type: "string"
      kpis:
        type: "array"
        items:
          $ref: "#/definitions/KpiRequest"
      dimensions:
        type: "array"
        items:
          $ref: "#/definitions/DimensionRequest"
      filters:
        type: "array"
        items:
          $ref: "#/definitions/FilterRequest"

  KpiRequest:
    type: "object"
    properties:
      name:
        type: "string"
      offeredMetric:
        type: "string"

  DimensionRequest:
    type: "object"
    properties:
      name:
        type: "string"

  FilterRequest:
    type: "object"
    properties:
      dimension:
        type: "string"
      kpi:
        type: "string"
      values:
        type: "array"
        items:
          type: "string"
      intervals:
        type: "array"
        items:
          type: "object"
          properties:
            lower:
              type: "string"
            upper:
              type: "string"
      isNegative:
        type: "boolean"

  DataResponse:
    type: "object"
    properties:
      header:
        type: "array"
        items:
          type: "object"
          properties:
            kpi:
              type: "string"
            offeredMetric:
              type: "string"
            dimension:
              type: "string"
      dataMatrix:
        type: "array"
        items:
          type: "array"
          items:
            type: "object"
