/**
 * NOTE: This class is auto generated by the swagger code generator program (2.2.3).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.DataRequest;
import io.swagger.model.DataResponse;

import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.CrossOrigin;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import java.util.List;
import javax.validation.constraints.*;
import javax.validation.Valid;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2018-02-13T21:19:23.429Z")

@Api(value = "data", description = "the data API")
@CrossOrigin(origins = "*")
public interface DataApi {

    @ApiOperation(value = "", notes = "", response = DataResponse.class, tags={ "Data", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Ok", response = DataResponse.class),
        @ApiResponse(code = 404, message = "Datasource not found", response = Void.class) })
    
    @RequestMapping(value = "/data",
        produces = { "application/json", "text/csv" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<DataResponse> dataPost(@ApiParam(value = "") @Valid @RequestBody DataRequest body);

}
