//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.02.13 at 10:58:58 PM CET 
//


package hu.denes.bme.dipterv.metadata;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the hu.denes.bme.dipterv.metadata package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: hu.denes.bme.dipterv.metadata
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Metadata }
     * 
     */
    public Metadata createMetadata() {
        return new Metadata();
    }

    /**
     * Create an instance of {@link Metadata.Kpi }
     * 
     */
    public Metadata.Kpi createMetadataKpi() {
        return new Metadata.Kpi();
    }

    /**
     * Create an instance of {@link Metadata.BaseMetricCalculation }
     * 
     */
    public Metadata.BaseMetricCalculation createMetadataBaseMetricCalculation() {
        return new Metadata.BaseMetricCalculation();
    }

    /**
     * Create an instance of {@link Metadata.Dimension }
     * 
     */
    public Metadata.Dimension createMetadataDimension() {
        return new Metadata.Dimension();
    }

    /**
     * Create an instance of {@link Metadata.Kpi.Column }
     * 
     */
    public Metadata.Kpi.Column createMetadataKpiColumn() {
        return new Metadata.Kpi.Column();
    }

    /**
     * Create an instance of {@link Metadata.Kpi.OfferedMetric }
     * 
     */
    public Metadata.Kpi.OfferedMetric createMetadataKpiOfferedMetric() {
        return new Metadata.Kpi.OfferedMetric();
    }

}
