export const ACTION_TYPE = {
    RECEIVED_DATA_QUERY_ANSWER: "RECEIVED_DATA_QUERY_ANSWER",
    RECEIVED_KPI_LIST: "RECEIVED_KPI_LIST",
    RECEIVED_DIMENSION_LIST: "RECEIVED_DIMENSION_LIST",
    RECEIVED_DATASOURCE_LIST: "RECEIVED_DATASOURCE_LIST",

    SEND_DATA_QUERY: "SEND_DATA_QUERY",
    SEND_KPI_QUERY: "SEND_KPI_QUERY",
    SEND_DIMENSION_QUERY: "SEND_DIMENSION_QUERY",
    SEND_DATASOURCE_QUERY: "SEND_DATASOURCE_QUERY",

    REMOVE_DRILLDOWN: "REMOVE_DRILLDOWN",

    CREATE_MEASUREMENT: "CREATE_MEASUREMENT",
    CREATE_DRILLDOWN: "CREATE_DRILLDOWN"
}

export function requestDatasources(base_url) {
    return {actionType: ACTION_TYPE.SEND_DATASOURCE_QUERY, url: base_url + "/metadata/datasources"};
}
